'use strict'

// https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations
// Removed duplicate abbreviations by selecting one that I believe is more likely used.

// More timezones here: https://mainfacts.com/world-timezones-time-zones
// Pull them in as needed.

/* eslint-disable comma-spacing, standard/array-bracket-even-spacing */
const zoneMap = new Map([
  // more common
    [ / CDT/   , ' GMT-05'    ]
  , [ / CEST/  , ' GMT+02'    ]
  , [ / CET/   , ' GMT+01'    ]

  // alphabetically
  , [ / ACDT/  , ' GMT+10:30']
  , [ / ACST/  , ' GMT+09:30']
  , [ / ACT/   , ' GMT-05'   ]
  , [ / ACWST/ , ' GMT+08:45']
  , [ / ADT/   , ' GMT-03'   ]
  , [ / AEDT/  , ' GMT+11'   ]
  , [ / AEST/  , ' GMT+10'   ]
  , [ / AFT/   , ' GMT+04:30']
  , [ / AKDT/  , ' GMT-08'   ]
  , [ / AKST/  , ' GMT-09'   ]
  , [ / AMST/  , ' GMT-03'   ]
  , [ / AMT/   , ' GMT+04'   ]
  , [ / ART/   , ' GMT-03'   ]
  , [ / AST/   , ' GMT-04'   ]
  , [ / AWST/  , ' GMT+08'   ]
  , [ / AZOST/ , ' GMT+00'   ]
  , [ / AZOT/  , ' GMT-01'   ]
  , [ / AZT/   , ' GMT+04'   ]
  , [ / BDT/   , ' GMT+08'   ]
  , [ / BIOT/  , ' GMT+06'   ]
  , [ / BIT/   , ' GMT-12'   ]
  , [ / BOT/   , ' GMT-04'   ]
  , [ / BRST/  , ' GMT-02'   ]
  , [ / BRT/   , ' GMT-03'   ]
  , [ / BST/   , ' GMT+01'   ]
  , [ / BTT/   , ' GMT+06'   ]
  , [ / CAT/   , ' GMT+02'   ]
  , [ / CCT/   , ' GMT+06:30']
  , [ / CHADT/ , ' GMT+13:45']
  , [ / CHAST/ , ' GMT+12:45']
  , [ / CHOT/  , ' GMT+08'   ]
  , [ / CHOST/ , ' GMT+09'   ]
  , [ / CHST/  , ' GMT+10'   ]
  , [ / CHUT/  , ' GMT+10'   ]
  , [ / CIST/  , ' GMT-08'   ]
  , [ / CIT/   , ' GMT+08'   ]
  , [ / CKT/   , ' GMT-10'   ]
  , [ / CLST/  , ' GMT-03'   ]
  , [ / CLT/   , ' GMT-04'   ]
  , [ / COST/  , ' GMT-04'   ]
  , [ / COT/   , ' GMT-05'   ]
  , [ / CST/   , ' GMT-06'   ]
  , [ / CT/    , ' GMT+08'   ]
  , [ / CVT/   , ' GMT-01'   ]
  , [ / CWST/  , ' GMT+08:45']
  , [ / CXT/   , ' GMT+07'   ]
  , [ / DAVT/  , ' GMT+07'   ]
  , [ / DDUT/  , ' GMT+10'   ]
  , [ / DFT/   , ' GMT+01'   ]
  , [ / EASST/ , ' GMT-05'   ]
  , [ / EAST/  , ' GMT-06'   ]
  , [ / EAT/   , ' GMT+03'   ]
  , [ / ECT/   , ' GMT-05'   ]
  , [ / EDT/   , ' GMT-04'   ]
  , [ / EEST/  , ' GMT+03'   ]
  , [ / EET/   , ' GMT+02'   ]
  , [ / EGST/  , ' GMT+00'   ]
  , [ / EGT/   , ' GMT-01'   ]
  , [ / EIT/   , ' GMT+09'   ]
  , [ / EST/   , ' GMT-05'   ]
  , [ / FET/   , ' GMT+03'   ]
  , [ / FJT/   , ' GMT+12'   ]
  , [ / FKST/  , ' GMT-03'   ]
  , [ / FKT/   , ' GMT-04'   ]
  , [ / FNT/   , ' GMT-02'   ]
  , [ / GALT/  , ' GMT-06'   ]
  , [ / GAMT/  , ' GMT-09'   ]
  , [ / GET/   , ' GMT+04'   ]
  , [ / GFT/   , ' GMT-03'   ]
  , [ / GILT/  , ' GMT+12'   ]
  , [ / GIT/   , ' GMT-09'   ]
  , [ / GMT/   , ' GMT+00'   ]
  , [ / GST/   , ' GMT+04'   ]
  , [ / GYT/   , ' GMT-04'   ]
  , [ / HDT/   , ' GMT-09'   ]
  , [ / HAEC/  , ' GMT+02'   ]
  , [ / HST/   , ' GMT-10'   ]
  , [ / HKT/   , ' GMT+08'   ]
  , [ / HMT/   , ' GMT+05'   ]
  , [ / HOVST/ , ' GMT+08'   ]
  , [ / HOVT/  , ' GMT+07'   ]
  , [ / ICT/   , ' GMT+07'   ]
  , [ / IDLW/  , ' GMT-12'   ]
  , [ / IDT/   , ' GMT+03'   ]
  , [ / IOT/   , ' GMT+03'   ]
  , [ / IRDT/  , ' GMT+04:30']
  , [ / IRKT/  , ' GMT+08'   ]
  , [ / IRST/  , ' GMT+03:30']
  , [ / IST/   , ' GMT+01'   ]
  , [ / JST/   , ' GMT+09'   ]
  , [ / KALT/  , ' GMT+02'   ]
  , [ / KGT/   , ' GMT+06'   ]
  , [ / KOST/  , ' GMT+11'   ]
  , [ / KRAT/  , ' GMT+07'   ]
  , [ / KST/   , ' GMT+09'   ]
  , [ / LHST/  , ' GMT+10:30']
  , [ / LINT/  , ' GMT+14'   ]
  , [ / MAGT/  , ' GMT+12'   ]
  , [ / MART/  , ' GMT-09:30']
  , [ / MAWT/  , ' GMT+05'   ]
  , [ / MDT/   , ' GMT-06'   ]
  , [ / MET/   , ' GMT+01'   ]
  , [ / MEST/  , ' GMT+02'   ]
  , [ / MHT/   , ' GMT+12'   ]
  , [ / MIST/  , ' GMT+11'   ]
  , [ / MIT/   , ' GMT-09:30']
  , [ / MMT/   , ' GMT+06:30']
  , [ / MSK/   , ' GMT+03'   ]
  , [ / MST/   , ' GMT-07'   ]
  , [ / MUT/   , ' GMT+04'   ]
  , [ / MVT/   , ' GMT+05'   ]
  , [ / MYT/   , ' GMT+08'   ]
  , [ / NCT/   , ' GMT+11'   ]
  , [ / NDT/   , ' GMT-02:30']
  , [ / NFT/   , ' GMT+11'   ]
  , [ / NPT/   , ' GMT+05:45']
  , [ / NST/   , ' GMT-03:30']
  , [ / NT/    , ' GMT-03:30']
  , [ / NUT/   , ' GMT-11'   ]
  , [ / NZDT/  , ' GMT+13'   ]
  , [ / NZST/  , ' GMT+12'   ]
  , [ / OMST/  , ' GMT+06'   ]
  , [ / ORAT/  , ' GMT+05'   ]
  , [ / PDT/   , ' GMT-07'   ]
  , [ / PET/   , ' GMT-05'   ]
  , [ / PETT/  , ' GMT+12'   ]
  , [ / PGT/   , ' GMT+10'   ]
  , [ / PHOT/  , ' GMT+13'   ]
  , [ / PHT/   , ' GMT+08'   ]
  , [ / PKT/   , ' GMT+05'   ]
  , [ / PMDT/  , ' GMT-02'   ]
  , [ / PMST/  , ' GMT-03'   ]
  , [ / PONT/  , ' GMT+11'   ]
  , [ / PST/   , ' GMT-08'   ]
  , [ / PYST/  , ' GMT-03'   ]
  , [ / PYT/   , ' GMT-04'   ]
  , [ / RET/   , ' GMT+04'   ]
  , [ / ROTT/  , ' GMT-03'   ]
  , [ / SAKT/  , ' GMT+11'   ]
  , [ / SAMT/  , ' GMT+04'   ]
  , [ / SAST/  , ' GMT+02'   ]
  , [ / SBT/   , ' GMT+11'   ]
  , [ / SCT/   , ' GMT+04'   ]
  , [ / SDT/   , ' GMT-10'   ]
  , [ / SGT/   , ' GMT+08'   ]
  , [ / SLST/  , ' GMT+05:30']
  , [ / SRET/  , ' GMT+11'   ]
  , [ / SRT/   , ' GMT-03'   ]
  , [ / SST/   , ' GMT-11'   ]
  , [ / SYOT/  , ' GMT+03'   ]
  , [ / TAHT/  , ' GMT-10'   ]
  , [ / THA/   , ' GMT+07'   ]
  , [ / TFT/   , ' GMT+05'   ]
  , [ / TJT/   , ' GMT+05'   ]
  , [ / TKT/   , ' GMT+13'   ]
  , [ / TLT/   , ' GMT+09'   ]
  , [ / TMT/   , ' GMT+05'   ]
  , [ / TRT/   , ' GMT+03'   ]
  , [ / TOT/   , ' GMT+13'   ]
  , [ / TVT/   , ' GMT+12'   ]
  , [ / ULAST/ , ' GMT+09'   ]
  , [ / ULAT/  , ' GMT+08'   ]
  , [ / UYST/  , ' GMT-02'   ]
  , [ / UYT/   , ' GMT-03'   ]
  , [ / UZT/   , ' GMT+05'   ]
  , [ / VET/   , ' GMT-04'   ]
  , [ / VLAT/  , ' GMT+10'   ]
  , [ / VOLT/  , ' GMT+04'   ]
  , [ / VOST/  , ' GMT+06'   ]
  , [ / VUT/   , ' GMT+11'   ]
  , [ / WAKT/  , ' GMT+12'   ]
  , [ / WAST/  , ' GMT+02'   ]
  , [ / WAT/   , ' GMT+01'   ]
  , [ / WEST/  , ' GMT+01'   ]
  , [ / WET/   , ' GMT+00'   ]
  , [ / WIT/   , ' GMT+07'   ]
  , [ / WST/   , ' GMT+08'   ]
  , [ / YAKT/  , ' GMT+09'   ]
  , [ / YEKT/  , ' GMT+05'   ]
  , [ / YEKST/ , ' GMT+06'   ]
])

/**
 * Replaces timezone abbreviation like 'CDT' with the matching UTC offset
 * If no known timezone is encountered in the string, the original string is returned.
 *
 * @name ntz
 * @param {String} s original date/time string
 * @returns {String} with timezone abbreviation replaced
 */
function ntz(s) {
  for (const [ zone, replacement ] of zoneMap) {
    if (zone.test(s)) return s.replace(zone, replacement)
  }
  return s
}

ntz.zoneMap = zoneMap
module.exports = ntz
